version: "3.7"

services:

  core:
    build: ./core
    container_name: api-gestao-usuario
    # command: uwsgi app.ini
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: nginx-gestao-usuario
    ports:
      - "80:80"
    depends_on: 
      - core
      
  db:
    image: postgres:12-alpine
    container_name: db-gestao-usuario
    volumes:
      - ./.data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=users
    ports:
      - 5432:5432
    restart: always