version: '3.7'

services:
  core:
    build: .
    container_name: api-gestao-usuario
    command: python server.py run -h 0.0.0.0
    volumes:
      - ./:/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    container_name: db-gestao-usuario
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=users
      ports:
        - 5432:5432
      restart: always